## Artificial Neural Network

In [1]:
import sys
print(sys.executable)

/Users/atulhooda/coding/deep learning/tensorflow-env/bin/python


### Implementing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.21.0'

In [3]:
dataset = pd.read_csv(
    "Deep Learning A-Z/Part 1 - Artificial Neural Networks (ANN)/Churn_Modelling.csv"
)
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
print(type(x))
print(x.shape)
print(x[:5])

<class 'numpy.ndarray'>
(10000, 10)
[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]]


### Encoding Categorical Data
Encoding the Independent Variable

Label encoding the "gender" column

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [5]:
print(x[0])

[619 'France' 0 42 2 0.0 1 1 1 101348.88]


OneHotEncoding the "Geography" Column

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [7]:
print(x.shape)
print(x[0])

(10000, 12)
[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


In [ ]:
print(x)

Splitting the dataset into test and train

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [12]:
print(x_train[0])

[0.0 0.0 1.0 667 'Female' 34 5 0.0 2 1 0 163830.64]


feature scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

## Part 2 - Building the ANN
Initialising the ANN

In [11]:
ann = tf.keras.models.Sequential()

Adding the fist input layer and first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the output input layer and first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

### Part 3 - Training the ANN
Compliting the ANN

In [15]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

Training the ANN on the training set

In [16]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 288us/step - accuracy: 0.7832 - loss: 0.5361
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7984 - loss: 0.4617
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 262us/step - accuracy: 0.8079 - loss: 0.4391
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 256us/step - accuracy: 0.8104 - loss: 0.4299
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step - accuracy: 0.8151 - loss: 0.4238
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.8190 - loss: 0.4195
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.8248 - loss: 0.4159
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.8249 - loss: 0.4133
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.8269 - loss: 0.4110
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.8288 - loss: 0.4088
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 257us/step - accuracy: 0.8289 - loss: 0.4071
Epoch 12/100
250/25

### Q. Use our ANN model to predict if the customer with the following information will leave the bank

In [17]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[0.02153233]]


In [18]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[[False]]


Predicting the Test set results

In [19]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 237us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1533   62]
 [ 212  193]]


0.863