## Artificial Neural Network

In [5]:
import sys
print(sys.executable)

/opt/miniconda3/bin/python


### Implementing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.21.0'

In [4]:
dataset = pd.read_csv(
    "Deep Learning A-Z/Part 1 - Artificial Neural Networks (ANN)/Churn_Modelling.csv"
)
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [14]:
print(type(x))
print(x.shape)
print(x[:5])

<class 'numpy.ndarray'>
(10000, 10)
[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]]


### Encoding Categorical Data
Encoding the Independent Variable

Label encoding the "gender" column

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,-2] = le.fit_transform(x[:,-2])

OneHotEncoding the "Geography" Column

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [19]:
print(x)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


Splitting the dataset into test and train

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

feature scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

## Part 2 - Building the ANN
Initialising the ANN

In [24]:
ann = tf.keras.models.Sequential()

Adding the fist input layer and first hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the second hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the output input layer and first hidden layer

In [27]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

### Part 3 - Training the ANN
Compliting the ANN

In [28]:
ann.compile(optimizer='adam',loss='mean_squared_error')